version: '3.8'

services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000